### ISSUE TITLE
Add option to customize progressbar color

### ISSUE THREAD

**Issue by techscientist** [vlonjatg/progress-activity#12]
This would be a greatly needed customization attribute for this library! Nice work!

**Comment by LOG-TAG** [comment]
this is much needed one! but   <item name="colorControlActivated">@color/colorAccent</item> this will work!

**Comment by vlonjat-gashi** [comment]
On the latest version v2.0.2 you can customize the color of the progress bar with the attribute `loadingProgressBarColor`. Sorry for the delay!
