### ISSUE TITLE
v2.0.4 not available !!

### ISSUE THREAD

**Issue by LOG-TAG** [vlonjatg/progress-activity#23]
` implementation 'com.github.vlonjatg:progress-activity:v2.0.3'`

not work please release it in jitpack!  http://www.methodscount.com/?lib=com.github.vlonjatg%3Aprogress-activity%3Av2.0.4

**Comment by vlonjat-gashi** [comment]
@LOG-TAG,

Sorry for the late reply. There was an issue with jitpack, which I just fixed in version `2.0.5` of the library.

**Comment by LOG-TAG** [comment]
can we get the lib with SDK update and CL constraint-layout:1.1.2' latest one?
