### ISSUE TITLE
How to hide?

### ISSUE THREAD

**Issue by Isabellle** [vlonjatg/progress-activity#9]
I'm sorry to ask this, but after doing progressActivity.showLoading() - I don't find any method like progressActivity.StopLoading; can you please point me to the right method to hide loading? Thanks!

**Comment by vlonjat-gashi** [comment]
@Isabellle, the way to stop loading is by calling progressActivity.showContent(). This will hide the loading bar and show the content.

**Comment by Isabellle** [comment]
Thank you!
